package AccountPattern.APP;

/*Generated by MPS */

import org.modellwerkstatt.objectflow.ObjectFlowRT.IOFXEntity;
import org.modellwerkstatt.objectflow.ObjectFlowRT.OFXInteger;
import org.modellwerkstatt.objectflow.ObjectFlowRT.OFXList;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.modellwerkstatt.objectflow.ObjectFlowRT.IOFXRevertableObject;
import java.util.List;

public class Acc_Document implements IOFXEntity<Integer> {
  public static final int entitySessionUID = Acc_Document.class.hashCode();
  protected boolean _dirty = true;
  protected boolean _readOnly = false;
  protected int _TCN = 0;

  public void setDirty(boolean value) {
    this._dirty = value;
  }

  public boolean getDirty() {
    return this._dirty;
  }

  public void setReadOnly(boolean value) {
    this._readOnly = value;
  }

  public boolean getReadOnly() {
    return this._readOnly;
  }

  public void clearDirtySetReadonly(boolean readOnly) {
    this._readOnly = readOnly;
    this._dirty = false;
  }

  public void setTCN(int value) {
    this._TCN = value;
  }

  public int getTCN() {
    return this._TCN;
  }

  public Integer getKey() {
    return this.id.getValue();
  }

  public int getSessionObjectKeyStoreID() {
    return entitySessionUID;
  }


  protected boolean _enabled = true;

  public void setEnabled(boolean value) {
    this._enabled = value;
  }

  public boolean getEnabled() {
    return this._enabled;
  }

  public Acc_Document _META() {
    return this;
  }



  protected OFXInteger id = new OFXInteger();
  protected OFXList<Acc_StockTransaction> transactions = new OFXList<Acc_StockTransaction>();


  public Acc_Document() {
  }

  public void addTranscation(Acc_StockTransaction ta) {
    if (ListSequence.fromList(getTransactions()).contains(ta)) {
      return;
    }
    ListSequence.fromList(getTransactions()).addElement(ta);

  }




  public OFXInteger getId_META() {
    return this.id;
  }

  public OFXList getTransactions_META() {
    return this.transactions;
  }




  public void load(IOFXRevertableObject param) {
    Acc_Document entity = ((Acc_Document) param);
    this.id.load(entity.id);
    this.transactions.load(entity.transactions);
    this._dirty = entity._dirty;
    this._enabled = entity._enabled;
    this._TCN = entity._TCN;
    this._readOnly = entity._readOnly;
  }

  public IOFXRevertableObject copy() {
    Acc_Document entity = new Acc_Document();
    entity.id = this.id.copy();
    entity.transactions = this.transactions.copy();
    entity._dirty = this._dirty;
    entity._enabled = this._enabled;
    entity._TCN = this._TCN;
    entity._readOnly = this._readOnly;
    return entity;
  }



  public int getId() {
    return id.getValue();
  }

  public void setId(int value) {
    if ((_dirty |= id.setValue(value)) && this._readOnly) {
      throw new IllegalAccessError("Changing values in read only entity is not allowed.");
    }
  }

  public List<Acc_StockTransaction> getTransactions() {
    return transactions.getValue();
  }

  public void setTransactions(List<Acc_StockTransaction> value) {
    if ((_dirty |= transactions.setValue(value)) && this._readOnly) {
      throw new IllegalAccessError("Changing values in read only entity is not allowed.");
    }
  }
}
